### ISSUE TITLE
Issue in running bd-rhapsody files

### ISSUE THREAD

**Issue by paramitadutta14** [minoda-lab/universc#14]
Hi,
Thanks for developing the tool which should be very useful for any bioinformatician working on scRNA-seq data.
I am, however, facing an issue when running the package on bd-rhapsody files. I had Cellranger pre-installed, so downloaded the .git repository, and executed the following command:

launch_universc.sh \
        -R1 SAMPLE1_L003_R1_001.fastq.gz SAMPLE1_L004_R1_001.fastq.gz \
        -R2 SAMPLE1_L003_R2_001.fastq.gz SAMPLE1_L004_R2_001.fastq.gz \
        --id OutRes \
        -r ~/CellRanger/RefGenome_3.0/GRCh38 \
        -t bd-rhapsody \
        --localcores 8 \
        --localmem 128 \
        --verbose

However, the execution got stuck after copying the .fastq files into the output folder. The last few lines of the output log are:

converting input files to confer cellranger format ...
 adjustment parameters:
  barcodes: 0 bp at its head
  UMIs: -2 bp at its tail
 making technology-specific modifications ...
  ... remove adapter and phase blocks for bd-rhapsody

No change in the output log for more than 12 hours !! Please check the issue. Thank you.

**Comment by kbattenb** [comment]
Hi,

I am glad you found UniverSC interesting (and I hope it becomes useful too).
Before anything else, since you are using a pre-installed cellranger, can you confirm that the version of cellranger is 3.0.2 or at least not higher?
Using a more recent (but not open sourced) version of cellranger has been a source of problems in a few cases in the past, so please make sure of that first.

Kai Battenberg

**Comment by paramitadutta14** [comment]
Hi,
Thanks for your reply. I am using a pre-installed cell ranger, version 3.0.2. 
Paramita

**Comment by kbattenb** [comment]
Hi Paramita,

That should be fine.
Now, before UniverSC calls cellranger, it first reformats the input files to make the input files look as thought they are that of 10x (as you see in the log), and this portion is not multithreaded.
It is possible that your input files are rather huge.

Can you try again, but this time with a single input file pair with 10,000 reads to see if the issue is related to the input file size?

Thank you.

Kai Battenberg

**Comment by TomKellyGenetics** [comment]
Any updates on this? Note that long run times are expected for large files. How many lines or reads are in these files?

Due to long time to execute we recommend running these in a server environment as a background job so that they will continue to execute if your network connection drops. We cache the reformatted files so that Cell Ranger can be run again without waiting for prior steps if parameters need to be changed.
