### ISSUE TITLE
Error when running test file or any other file : error: Invalid value for '--lanes <NUMS>.

### ISSUE THREAD

**Issue by shobhitagrawal1** [minoda-lab/universc#7]
Dear Kai,
Great idea with the program, particularly relevant for me as I have several BD and 10X samples and need to be consistent with the pre-processing and need to compare the two platforms. 

I am having difficulties running the script . I am getting this error running the test fastq (for this github repo) or any other 10x fastq files:

error: Invalid value for '--lanes <NUMS>...': invalid digit found in string
my command :
 bash launch_universc.sh -R1 /home/user/tinygex_S1_L001_R1_001.fastq.gz -R2 /home/user/tinygex_S1_L001_R2_001.fastq.gz -i tests11 -r /home/referencefiles/refdata-gex-GRCh38-2020-A  -t 10x --localcores 48 -p

the installation seems to be ok, as i get the help menu (as expected) after setting up the necessary requirements regarding cellranger, path etc.  (Probably has something with the bashscript detecting the Lane number in the sample file name and assigning it a type cellranger doesn't recognize?)

Second, would be possible to include the option of --include-introns in the bashscript for cellranger as I am guessing many users might be interested in that (in the worst case I edit the bash file, but I just did not want to mess up things in my trial runs).

system: unix
cellranger: v.6 from the 10X genomics

thanks for this tool, and looking forward to your response
shobhit

**Comment by kbattenb** [comment]
Hi Shobhit,

I am glad you found UniverSC interesting.
There is one thing I would like you to try before trying anything else, which is to use cellranger v3.0.2 rather than cellranger v6.
UniverSC is not meant to be used with cellranger versions more recent than v3.0.2 due to copyright issues.
On a related note, this is the reason why we do not (or rather cannot) have —include-introns as an option.

Please let us know if you still have issues running the test data even after using v3.0.2.

Sorry for the trouble.

Kai Battenberg

**Comment by shobhitagrawal1** [comment]
Thanks I am on it

**Comment by TomKellyGenetics** [comment]
I've corrected this issue here on the development version: https://github.com/minoda-lab/universc/commit/eb3ae4e2477dab8d2e8665a13af1ef59a5497712#diff-6e90ec0cd1b248b4f5f6616376e5ab40ca509fd1ed5982a78ab6b07bf36119c5R1779

It should be resolved in the upcoming v1.2.5 release of UniverSC which we are testing now.

**Comment by TomKellyGenetics** [comment]
In the meantime please try rolling back to UniverSC v1.2.3 which does not have this issue. This is problem is due to recent changes following the announcement that Nova Seq X will support 16 lane flowcells (when 1-9 are supported currently).

**Comment by TomKellyGenetics** [comment]
Closed by v1.2.5 as discussed in #8
