### ISSUE TITLE
Doesn't work with another cellranger version 

### ISSUE THREAD

**Issue by ayyildizd** [minoda-lab/universc#9]
Hi, first of all thanks for developing such a useful tool.
I wanted to use this tool with cellranger 6.0.2 but It doesn't work. It is mainly because the program is looking for some files and folders which is not available anymore in version6. When I try the tool with cellranger 3.0.2 it does.
Are you maybe considering to update the launch script for these changes?

**Comment by kbattenb** [comment]
Hi ayyildizd,

I am glad you found UniverSC interesting.
Sorry to say, we are not updating UniverSC to use cellranger 6.0.2 due to copyright issues.
cellranger beyond 3.0.2 is not open sourced and are not allowed to use to handle data from any platform other than that of 10x.
So please stick to 3.0.2 (it should be fine for the most part anyway) and avoid using further updates to avoid any potential legal complications.

Kai Battenberg
